image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      sudo mkdir -p /var/run/mysqld && \
      sudo chown -R mysql:mysql /var/run/mysqld && \
      sudo chmod 755 /var/run/mysqld && \
      sudo service mysql start && \
      sudo mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '${MYSQL_ROOT_PASSWORD}';" || true && \
      mysql -u root -p"${MYSQL_ROOT_PASSWORD}" -e "CREATE DATABASE IF NOT EXISTS wordpress;"
  - name: Start Apache and MySQL
    command: |
      # Make sure Apache listens on port 8080
      sudo sed -i 's/Listen 80/Listen 8080/' /etc/apache2/ports.conf && \
      sudo sed -i 's/<VirtualHost *:80>/<VirtualHost *:8080>/' /etc/apache2/sites-available/000-default.conf && \
      sudo service apache2 start && \
      sudo service mysql start && \
      gp await-port 8080 && gp preview $(gp url 8080)

ports:
  - port: 8080
    onOpen: open-preview
  - port: 3306
    onOpen: ignore

vscode:
  extensions:
    - felixfbecker.php-debug
    - bmewburn.vscode-intelephense-client

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    addCheck: true
    addComment: true

# Environment variables should be set in Gitpod settings:
# MYSQL_ROOT_PASSWORD
# WP_ADMIN_USER
# WP_ADMIN_PASSWORD
# WP_ADMIN_EMAIL

