tasks:
  - name: docker-install
    # Pulling and building docker images for the environment
    init: |
      docker-compose pull
      docker-compose build
      echo "Docker images built. Starting Docker..."
    command: |
      gp sync-done docker
      docker-compose up -d  # Use detached mode to keep the terminal free for other commands

  - name: wordpress-install
    # Wait for Docker setup, configure WordPress with WP-CLI, set permissions
    init: |
      gp sync-await docker
      sleep 15  # Slightly increased delay to ensure DB is fully ready
      echo "Installing WordPress..."
      docker exec -it gitpod-wpdev-wordpress wp core install \
        --url="8000-${GITPOD_WORKSPACE_ID}.${GITPOD_WORKSPACE_CLUSTER_HOST}" \
        --title="Gitpod WordPress Development" \
        --admin_user="admin" \
        --admin_password="admin" \
        --admin_email="you@example.com" \
        --skip-email --allow-root
      # Set correct permissions for the Gitpod user and ensure web server compatibility
      sudo chmod -R 755 ./wp-core
      sudo chown -R gitpod:gitpod ./wp-core
      sudo chmod -R 755 ./wp-content
      sudo chown -R gitpod:gitpod ./wp-content
    # Opens WordPress in an external browser and tails Apache logs
    command: |
      gp preview $(gp url 8000) --external
      multitail ./.env/wp-apache-logs/access.log -I ./.env/wp-apache-logs/error.log

ports:
  - port: 8000
    onOpen: ignore
  - port: 8080
    onOpen: ignore

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - johnbillion.vscode-wordpress-hooks
