image:
  file: .gitpod.Dockerfile

tasks:
  - name: Setup and Start WordPress Multisite
    init: |
      sudo service mysql start
      sudo mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '${MYSQL_ROOT_PASSWORD}';" || true
      mysql -u root -p"${MYSQL_ROOT_PASSWORD}" -e "CREATE DATABASE IF NOT EXISTS wordpress;"
      if [ ! -f /workspace/multisite/wordpress/wp-config.php ]; then
        wp core download --path=/workspace/multisite/wordpress
        SITE_URL=$(gp url 80)
        wp config create --dbname=wordpress --dbuser=root --dbpass="${MYSQL_ROOT_PASSWORD}" --dbhost=localhost --path=/workspace/multisite/wordpress
        wp core multisite-install --url="${SITE_URL}" \
          --title="Gitpod Multisite" \
          --admin_user="${WP_ADMIN_USER}" \
          --admin_password="${WP_ADMIN_PASSWORD}" \
          --admin_email="${WP_ADMIN_EMAIL}" \
          --path=/workspace/multisite/wordpress
        echo "WordPress Multisite installed successfully!"
      else
        echo "WordPress is already installed."
      fi
    command: |
      sudo service mysql start
      sudo service apache2 restart
      gp ports await 80 && gp preview $(gp url 80)

ports:
  - port: 80
    onOpen: open-preview
  - port: 3306
    onOpen: ignore

vscode:
  extensions:
    - felixfbecker.php-debug
    - bmewburn.vscode-intelephense-client

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    addCheck: true
    addComment: true
