image:
  file: .gitpod.Dockerfile

tasks:
  - name: Setup and Start WordPress Multisite
    init: |
      # Start MySQL service
      sudo service mysql start

      # Set up MySQL root password if not already set
      sudo mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '${MYSQL_ROOT_PASSWORD}';" || true

      # Create MySQL database for WordPress
      mysql -u root -p"${MYSQL_ROOT_PASSWORD}" -e "CREATE DATABASE IF NOT EXISTS wordpress;"

      # Ensure WordPress is not already downloaded to prevent overwriting
      if [ ! -f /workspace/multisite/wordpress/wp-config.php ]; then
        # Download WordPress
        wp core download --path=/workspace/multisite/wordpress

        # Get the Gitpod workspace URL dynamically
        SITE_URL=$(gp url 80)

        # Set up wp-config.php with database details
        wp config create --dbname=wordpress --dbuser=root --dbpass="${MYSQL_ROOT_PASSWORD}" --dbhost=localhost --path=/workspace/multisite/wordpress

        # Install WordPress Multisite
        wp core multisite-install --url="${SITE_URL}" \
          --title="Gitpod Multisite" \
          --admin_user="${WP_ADMIN_USER}" \
          --admin_password="${WP_ADMIN_PASSWORD}" \
          --admin_email="${WP_ADMIN_EMAIL}" \
          --path=/workspace/multisite/wordpress

        echo "WordPress Multisite installed successfully!"
      else
        echo "WordPress is already installed."
      fi

    command: |
      # Start services
      sudo service mysql start
      sudo service apache2 start

      # Wait for Gitpod to open port 80 and preview the site
      gp await-port 80 && gp preview $(gp url 80)

ports:
  - port: 80
    onOpen: open-preview
  - port: 3306
    onOpen: ignore

vscode:
  extensions:
    - felixfbecker.php-debug
    - bmewburn.vscode-intelephense-client

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    addCheck: true
    addComment: true

# The following environment variables should be set in Gitpod's environment variables settings:
# MYSQL_ROOT_PASSWORD
# WP_ADMIN_USER
# WP_ADMIN_PASSWORD
# WP_ADMIN_EMAIL
