image:
  file: .gitpod.Dockerfile

tasks:
  - name: Setup WordPress Multisite
    init: |
      # Start MySQL and create a WordPress database
      sudo service mysql start || sudo /etc/init.d/mysql start
      mysql -u root -p"${MYSQL_ROOT_PASSWORD}" -e "CREATE DATABASE IF NOT EXISTS wordpress;"

      # Install WP-CLI if not already installed
      if ! command -v wp &> /dev/null; then
        curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
        chmod +x wp-cli.phar
        sudo mv wp-cli.phar /usr/local/bin/wp
      fi

      # Download WordPress core if not already downloaded
      if [ ! -f /workspace/multisite/wordpress/wp-config.php ]; then
        wp core download --path=/workspace/multisite/wordpress
      fi

      # Generate wp-config.php
      wp config create --dbname=wordpress --dbuser=root --dbpass="${MYSQL_ROOT_PASSWORD}" --dbhost=localhost --path=/workspace/multisite/wordpress

      # Install WordPress Multisite
      SITE_URL=$(gp url 80)
      wp core multisite-install --url="${SITE_URL}" \
        --title="Gitpod Multisite" \
        --admin_user="${WP_ADMIN_USER}" \
        --admin_password="${WP_ADMIN_PASSWORD}" \
        --admin_email="${WP_ADMIN_EMAIL}" \
        --path=/workspace/multisite/wordpress

    command: |
      # Start services
      sudo service mysql start && sudo service php8.3-fpm start && sudo nginx -g 'daemon off;'
